services:
    springboot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - SPRING_PROFILES_ACTIVE=production
            - DB_URL=jdbc:mariadb://mariadb:3306/database
            - DB_USERNAME=admin
            - DB_PASSWORD=password
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
        ports:
            - "8080:8080"
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - app-network

    mariadb:
        image: mariadb:12.0.2
        environment:
            MARIADB_ROOT_PASSWORD: rootpassword
            MARIADB_DATABASE: database
            MARIADB_USER: admin
            MARIADB_PASSWORD: password
        ports:
            - "3306"
        volumes:
            - mariadb-data:/var/lib/mysql
            - ./init-scripts:/docker-entrypoint-initdb.d
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s

networks:
    app-network:
        driver: bridge
volumes:
    mariadb-data:
